### ISSUE TITLE
Remove bounds on `T` for `Debug`, `PartialEq` and `Hash` impls

### ISSUE THREAD

**Issue by lopopolo** [artichoke/raw-parts#12]
`RawParts` derives `Debug`, `PartialEq`, and `Hash`. The derive macros from `core` add bounds on `T` even when they are not required, as is the case with the `T` in `RawParts` which is only a pointer and impls these traits regardless of what `T` is.

Remove the derived impls and manually implement these traits.

Such a change warrants a minor version bump.

**Comment by molinarim** [comment]
I've been looking to get back into rust and have been following artichoke for a while now, I would like to work on this.

**Comment by lopopolo** [comment]
Thanks @molinarim it's all yours. Looking forward to your PR.

**Comment by molinarim** [comment]
@lopopolo Sorry I've been taking so long on this issue, I'm a little rustier than I realized. I do have a couple of questions I hope you can answer:

1. For PartialEq, should it compare the raw parts themselves or just compare the pointer to show that the vector's are the same?
https://github.com/molinarim/raw-parts/blob/68a1fc8d14824da540ecbd294f147e9ed993297b/src/lib.rs#L134-L140
2. For Hash, should every part get hashed or just the ptr?

**Comment by lopopolo** [comment]
@molinarim I think for now, let's keep the manual impls the same as the derived ones, which means that every property is checked for equality and every property is hashed.

**Comment by lopopolo** [comment]
@molinarim for this bit, you can use `f.debug_struct`.

https://github.com/molinarim/raw-parts/blob/68a1fc8d14824da540ecbd294f147e9ed993297b/src/lib.rs#L128-L132

https://doc.rust-lang.org/stable/std/fmt/struct.Formatter.html#method.debug_struct

**Comment by molinarim** [comment]
Thanks for the insights! I'll get back on it shortly.
